spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pipealvz/gradle-config
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}
server:
  port: 9000